# Copyright 2026 ZyvorAI Labs Private Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Builds the `chaos_inject` fault-injection shell script -- mechanical
string templating, deliberately NOT LLM-generated (a fixed `tc netem`/
`iptables` invocation needs no model call, unlike exploit_poc's PoC
generation, which has real ambiguity to resolve).

Honest scope note: `latency`/`packet_loss` apply `tc netem` at the pod's
network *interface* level, not scoped to the target destination by a tc
traffic filter (that would need a classful qdisc + a `tc filter` match,
meaningfully more complex tc configuration this pass didn't attempt to
build un-verified). In practice this is still target-scoped in effect,
because the sandboxed pod's only real egress traffic is to the one target
(plus DNS) -- the same best-effort scoping story as the exploit sandbox's
own per-Job NetworkPolicy (see `kubernetes/sandbox.yaml`). `connection_reset`/
`dependency_timeout` use `iptables` rules matched on destination host/port,
which genuinely are target-scoped with no such caveat.

This was never executed against a real network interface during
development -- no Kubernetes cluster was reachable, and running real `tc`/
`iptables` commands against this development machine's own network would
be an inappropriate, unauthorized action regardless of cluster
availability. Only the generated *text* is verified (see
tests/unit/test_chaos_inject_script.py); the runtime behavior is
unit-tested only, named honestly in ROADMAP.md.
"""

from __future__ import annotations

FAULT_TYPES = ("latency", "packet_loss", "connection_reset", "dependency_timeout")


class InjectScriptError(ValueError):
    pass


def build_injection_script(
    *,
    fault_type: str,
    target_host: str,
    target_port: int,
    latency_ms: int,
    packet_loss_pct: int,
    duration_s: int,
    interface: str = "eth0",
) -> str:
    if fault_type not in FAULT_TYPES:
        raise InjectScriptError(f"unsupported fault_type: {fault_type!r}")

    if fault_type == "latency":
        apply_cmd = f"tc qdisc add dev {interface} root netem delay {latency_ms}ms"
        teardown_cmd = f"tc qdisc del dev {interface} root"
    elif fault_type == "packet_loss":
        apply_cmd = f"tc qdisc add dev {interface} root netem loss {packet_loss_pct}%"
        teardown_cmd = f"tc qdisc del dev {interface} root"
    elif fault_type == "connection_reset":
        apply_cmd = f"iptables -A OUTPUT -p tcp -d {target_host} --dport {target_port} -j REJECT --reject-with tcp-reset"
        teardown_cmd = f"iptables -D OUTPUT -p tcp -d {target_host} --dport {target_port} -j REJECT --reject-with tcp-reset"
    else:  # dependency_timeout
        apply_cmd = f"iptables -A OUTPUT -p tcp -d {target_host} --dport {target_port} -j DROP"
        teardown_cmd = f"iptables -D OUTPUT -p tcp -d {target_host} --dport {target_port} -j DROP"

    return f"""#!/bin/sh
# Generated by agents/chaos/inject_script.py -- mechanical, not LLM-generated.
set -eu

# A bare foreground `sleep` is NOT interruptible by a trap in sh -- the trap
# only runs once the foreground command completes, so a signal sent during
# a bare `sleep {duration_s}` would silently wait out the full duration
# before tearing anything down (confirmed the hard way in development: the
# first version of this script did exactly that). Backgrounding sleep and
# `wait`-ing on it makes the wait interruptible, and the trap must also
# explicitly kill that child -- the trap firing does NOT by itself stop an
# already-backgrounded sibling process.
teardown() {{
    trap - EXIT INT TERM
    {teardown_cmd} 2>/dev/null || true
    if [ -n "${{SLEEP_PID:-}}" ]; then
        kill "$SLEEP_PID" 2>/dev/null || true
    fi
    echo 'RESULT: {{"phase": "teardown_complete"}}'
}}
trap teardown EXIT INT TERM

echo 'RESULT: {{"phase": "fault_applied", "fault_type": "{fault_type}"}}'
{apply_cmd}
sleep {duration_s} &
SLEEP_PID=$!
wait "$SLEEP_PID"
"""
